import{S as q,a as S,i as n}from"./assets/vendor-NeYdtwFS.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&t(u)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();const P=new q(".gallery a",{captionsData:"alt",captionDelay:250});function b(e){const o=document.querySelector(".gallery");if(!o)return;const a=e.map(t=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${t.largeImageURL}" title="${t.tags}">
          <img
            class="gallery-image"
            src="${t.webformatURL}"
            alt="${t.tags}"
            loading="lazy"
          />
        </a>
        <ul class="stats">
          <li class="stats-item"><b>Likes</b> ${t.likes}</li>
          <li class="stats-item"><b>Views</b> ${t.views}</li>
          <li class="stats-item"><b>Comments</b> ${t.comments}</li>
          <li class="stats-item"><b>Downloads</b> ${t.downloads}</li>
        </ul>
      </li>
    `).join("");o.insertAdjacentHTML("beforeend",a),P.refresh()}function p(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function w(){const e=document.querySelector(".loader");e&&(e.style.display="block")}function f(){const e=document.querySelector(".loader");e&&(e.style.display="none")}function L(){const e=document.querySelector(".load-more");e&&(e.style.display="block")}function y(){const e=document.querySelector(".load-more");e&&(e.style.display="none")}const M="52790584-b8940124ef420833efbac5129",h=15;async function E(e,o){try{return(await S.get("https://pixabay.com/api/",{params:{q:e,key:M,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:h,page:o}})).data}catch(a){throw a}}let m="",i=1,l=0;const g=document.querySelector(".form"),d=document.querySelector(".gallery"),c=document.querySelector(".load-more");c.addEventListener("click",async()=>{if(c.disabled=!0,w(),l&&i>l){n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),y(),f(),c.disabled=!1;return}try{const e=await E(m,i);if(b(e.hits),i+=1,e.totalHits!=null&&(l=Math.ceil(e.totalHits/h)),d.firstElementChild&&d.firstElementChild.getBoundingClientRect){const o=d.firstElementChild.getBoundingClientRect().height*2;window.scrollBy({top:o,behavior:"smooth"})}i>l?y():L()}catch(e){n.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error("Error fetching more images:",e)}finally{f(),c.disabled=!1}});g.addEventListener("submit",R);async function R(e){e.preventDefault();const a=new FormData(g).get("search-text").trim();if(a===""){n.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}m=a,i=1,l=0,w(),p();try{const t=await E(m,i);if(!t||!Array.isArray(t.hits)||t.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),p();return}b(t.hits),i+=1,t.totalHits!=null&&(l=Math.ceil(t.totalHits/h)),i<=l?L():y()}catch(t){n.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error("Error fetching images:",t)}finally{f(),g.reset()}}
//# sourceMappingURL=index.js.map
